include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: warning
    todo: ignore

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_final_locals
    - avoid_unnecessary_containers
    - close_sinks
    - prefer_expression_function_bodies
    - avoid_catches_without_on_clauses
